
# 自分がOPになるための設定
# http://localhost:4000/.well-known/openid-configuration
development: &defaults
  issuer: http://localhost:4000

test:
  <<: *defaults

production:
  <<: *defaults
  issuer: https://connect-op.herokuapp.com
